//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUsers
    {
        public int UserID { get; set; }
        public string LoginName { get; set; }
        public string PasswordKey { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> StaffID { get; set; }
    
        public virtual AppRoles AppRoles { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
