//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Components
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Components()
        {
            this.CurrentInventory = new HashSet<CurrentInventory>();
            this.ProductStructure = new HashSet<ProductStructure>();
        }
    
        public int ComponentID { get; set; }
        public string SerialCode { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> MeasureID { get; set; }
        public Nullable<decimal> MinBalance { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Measures Measures { get; set; }
        public virtual ComponentTypes ComponentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentInventory> CurrentInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStructure> ProductStructure { get; set; }
    }
}
