//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentInventory
    {
        public int InventoryID { get; set; }
        public Nullable<int> StorageID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual Storages Storages { get; set; }
    }
}
