//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int EquipmentID { get; set; }
        public string InventoryNumber { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string MaintenanceSchedule { get; set; }
    
        public virtual EquipModels EquipModels { get; set; }
        public virtual EquipStatuses EquipStatuses { get; set; }
        public virtual EquipTypes EquipTypes { get; set; }
    }
}
