//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.ProductStructure = new HashSet<ProductStructure>();
            this.WorkRoutes = new HashSet<WorkRoutes>();
        }
    
        public int ItemID { get; set; }
        public string SKU { get; set; }
        public string FullTitle { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Details { get; set; }
        public Nullable<int> MeasureID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Measures Measures { get; set; }
        public virtual ItemStatuses ItemStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStructure> ProductStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkRoutes> WorkRoutes { get; set; }
    }
}
