//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartLogisticsEntities : DbContext
    {
        public SmartLogisticsEntities()
            : base("name=SmartLogisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppRoles> AppRoles { get; set; }
        public virtual DbSet<AppUsers> AppUsers { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Components> Components { get; set; }
        public virtual DbSet<ComponentTypes> ComponentTypes { get; set; }
        public virtual DbSet<CurrentInventory> CurrentInventory { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipModels> EquipModels { get; set; }
        public virtual DbSet<EquipStatuses> EquipStatuses { get; set; }
        public virtual DbSet<EquipTypes> EquipTypes { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemStatuses> ItemStatuses { get; set; }
        public virtual DbSet<JobTitles> JobTitles { get; set; }
        public virtual DbSet<Measures> Measures { get; set; }
        public virtual DbSet<PaymentTypes> PaymentTypes { get; set; }
        public virtual DbSet<ProductStructure> ProductStructure { get; set; }
        public virtual DbSet<SkillLevels> SkillLevels { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffStatuses> StaffStatuses { get; set; }
        public virtual DbSet<Storages> Storages { get; set; }
        public virtual DbSet<StorageTypes> StorageTypes { get; set; }
        public virtual DbSet<SupplyOrders> SupplyOrders { get; set; }
        public virtual DbSet<SupplyStatuses> SupplyStatuses { get; set; }
        public virtual DbSet<Vendors> Vendors { get; set; }
        public virtual DbSet<WorkOperations> WorkOperations { get; set; }
        public virtual DbSet<WorkRoutes> WorkRoutes { get; set; }
    }
}
