//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.AppUsers = new HashSet<AppUsers>();
            this.SupplyOrders = new HashSet<SupplyOrders>();
        }
    
        public int StaffID { get; set; }
        public string Phone { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUsers> AppUsers { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual JobTitles JobTitles { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual SkillLevels SkillLevels { get; set; }
        public virtual StaffStatuses StaffStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyOrders> SupplyOrders { get; set; }
    }
}
