//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrders
    {
        public int OrderID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> StorageID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Storages Storages { get; set; }
        public virtual SupplyStatuses SupplyStatuses { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
