//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOperations
    {
        public int OperationID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public string OpName { get; set; }
        public Nullable<int> StepNumber { get; set; }
        public Nullable<int> TimeLimitMinutes { get; set; }
    
        public virtual WorkRoutes WorkRoutes { get; set; }
    }
}
